Fix field parsing in require-field-index (#799)
Hi folks, thanks for this project!

Quick fix here - in my app `require-field-index` is throwing an error on
models that have `@@unique` with a name followed by fields defined in an
array, like:

```
model Foo {
  // ...
  @@unique(name: "some_unique_constraint", [field1, field2])
}
```

which results in:

```
    TypeError: Cannot read properties of undefined (reading 'value')

      222 |         return false;
      223 |       })?.value as KeyValue
    > 224 |     ).value;
          |       ^
      225 |
      226 |     if (fieldsValue == null) {
      227 |       throw new Error(

      at extractPrimaryFieldNameFromRelationListAttribute (src/rules/require-field-index.ts:224:7)
      at src/rules/require-field-index.ts:191:15
```

So adding a test and fixing the field parsing there.