require-field-index: add support for functions in indexes (#774)
I wanted to enable the `require-field-index` in my project when I got an
error message:
```
Error: value is not a string array {"type":"function","name":"endDate","params":[{"type":"keyValue","key":"sort","value":"Desc","location":{"startLine":125,"startColumn":19,"startOffset":4111,"endLine":125,"endColumn":22,"endOffset":4114}}],"location":{"startLine":125,"startColumn":11,"startOffset":4103,"endLine":125,"endColumn":17,"endOffset":4109}}
    at assertValueIsStringArray (file:///Users/<...>/node_modules/prisma-lint/dist/common/prisma.js:83:11)
```

The line that failed the parsing here is an index with a `sort` option
set ([relevant Prisma
docs](https://www.prisma.io/docs/orm/prisma-schema/data-model/indexes#configuring-the-index-sort-order-with-sort)):
```prisma
@@index([endDate(sort: Desc)])
```

I gave a stab at fixing this myself, let me know what you think!